# Lambda School Data Science - Logistic Regression

Logistic regression is the baseline for classification models, as well as a handy way to predict probabilities (since those too live in the unit interval). While relatively simple, it is also the foundation for more sophisticated classification techniques such as neural networks (many of which can effectively be thought of as networks of logistic models).

## Lecture - Where Linear goes Wrong
### Return of the Titanic 🚢

You've likely already explored the rich dataset that is the Titanic - let's use regression and try to predict survival with it. The data is [available from Kaggle](https://www.kaggle.com/c/titanic/data), so we'll also play a bit with [the Kaggle API](https://github.com/Kaggle/kaggle-api).

### Get data, option 1: Kaggle API

#### Sign up for Kaggle and get an API token
1. [Sign up for a Kaggle account](https://www.kaggle.com/), if you don’t already have one. 
2. [Follow these instructions](https://github.com/Kaggle/kaggle-api#api-credentials) to create a Kaggle “API Token” and download your `kaggle.json` file. If you are using Anaconda, put the file in the directory specified in the instructions.

_This will enable you to download data directly from Kaggle. If you run into problems, don’t worry — I’ll give you an easy alternative way to download today’s data, so you can still follow along with the lecture hands-on. And then we’ll help you through the Kaggle process after the lecture._

#### Put `kaggle.json` in the correct location

- ***If you're using Anaconda,*** put the file in the directory specified in the [instructions](https://github.com/Kaggle/kaggle-api#api-credentials).

- ***If you're using Google Colab,*** upload the file to your Google Drive, and run this cell:

In [0]:
from google.colab import drive
drive.mount('/content/drive')
%env KAGGLE_CONFIG_DIR=/content/drive/My Drive/

#### Install the Kaggle API package and use it to get the data

You also have to join the Titanic competition to have access to the data

In [0]:
!pip install kaggle

In [0]:
!kaggle competitions download -c titanic

### Get data, option 2: Download from the competition page
1. [Sign up for a Kaggle account](https://www.kaggle.com/), if you don’t already have one. 
2. [Go to the Titanic competition page](https://www.kaggle.com/c/titanic) to download the [data](https://www.kaggle.com/c/titanic/data).

### Get data, option 3: Use Seaborn

```
import seaborn as sns
train = sns.load_dataset('titanic')
```

But Seaborn's version of the Titanic dataset is not identical to Kaggle's version, as we'll see during this lesson!

### Read data

In [1]:
import pandas as pd
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train.shape, test.shape

((891, 12), (418, 11))

In [3]:
train.sample(n=3)

PassengerId  Survived  Pclass                    Name     Sex   Age  \
881          882         0       3      Markun, Mr. Johann    male  33.0   
64            65         0       1   Stewart, Mr. Albert A    male   NaN   
2              3         1       3  Heikkinen, Miss. Laina  female  26.0   

     SibSp  Parch            Ticket     Fare Cabin Embarked  
881      0      0            349257   7.8958   NaN        S  
64       0      0          PC 17605  27.7208   NaN        C  
2        0      0  STON/O2. 3101282   7.9250   NaN        S

In [4]:
test.sample(n=3)

PassengerId  Pclass                               Name   Sex   Age  \
310         1202       3               Cacic, Mr. Jego Grga  male  18.0   
129         1021       3               Petersen, Mr. Marius  male  24.0   
54           946       2  Mangiavacchi, Mr. Serafino Emilio  male   NaN   

     SibSp  Parch       Ticket     Fare Cabin Embarked  
310      0      0       315091   8.6625   NaN        S  
129      0      0       342441   8.0500   NaN        S  
54       0      0  SC/A.3 2861  15.5792   NaN        C

In [12]:
target= 'Survived'
train[target].value_counts(normalize=True)#to see in percentage

0    0.616162
1    0.383838
Name: Survived, dtype: float64

In [13]:
train.describe(include='number')

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [14]:
train.describe(exclude='number')

Name   Sex  Ticket        Cabin Embarked
count                               891   891     891          204      889
unique                              891     2     681          147        3
top     Brocklebank, Mr. William Alfred  male  347082  C23 C25 C27        S
freq                                  1   577       7            4      644

### How would we try to do this with linear regression?

https://scikit-learn.org/stable/modules/impute.html

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

features = ['Pclass', 'Age', 'Fare']
target = 'Survived'
X_train = train[features]
y_train = train[target]
X_test = test[features]

imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train)

X_test_imputed = imputer.fit_transform(X_train)
lin_reg = LinearRegression()
lin_reg.fit(X_train_imputed, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [29]:
X_train.head(6)

Pclass   Age     Fare
0       3  22.0   7.2500
1       1  38.0  71.2833
2       3  26.0   7.9250
3       1  35.0  53.1000
4       3  35.0   8.0500
5       3   NaN   8.4583

In [30]:
X_train_imputed[:6]#made into a numpy array

array([[ 3.        , 22.        ,  7.25      ],
       [ 1.        , 38.        , 71.2833    ],
       [ 3.        , 26.        ,  7.925     ],
       [ 1.        , 35.        , 53.1       ],
       [ 3.        , 35.        ,  8.05      ],
       [ 3.        , 29.69911765,  8.4583    ]])

In [31]:
X_train['Age'].mean()

29.69911764705882

In [32]:
X_test.tail()

Pclass   Age      Fare
413       3   NaN    8.0500
414       1  39.0  108.9000
415       3  38.5    7.2500
416       3   NaN    8.0500
417       3   NaN   22.3583

In [33]:
X_test_imputed[-5:]#applied mean from training dataset
#if you fill in NaN with mean, you should be using training mean in test
#you don't want to leak test dataset. 

array([[ 2.        , 27.        , 13.        ],
       [ 1.        , 19.        , 30.        ],
       [ 3.        , 29.69911765, 23.45      ],
       [ 1.        , 26.        , 30.        ],
       [ 3.        , 32.        ,  7.75      ]])

In [36]:
import numpy as np
test_case = np.array([[1, 5, 500]])#Rich 5-yearold as first class
lin_reg.predict(test_case)

array([1.19207871])

In [37]:
y_pred = lin_reg.predict(X_test_imputed)

In [39]:
pd.Series(y_pred).describe()

count    891.000000
mean       0.383838
std        0.192072
min       -0.105916
25%        0.225843
50%        0.320840
75%        0.512450
max        0.980598
dtype: float64

In [40]:
pd.Series(lin_reg.coef_, X_train.columns)

Pclass   -0.210390
Age      -0.007358
Fare      0.000751
dtype: float64

In [41]:
lin_reg.intercept_

1.0638995000035438

In [42]:
#if our fare is high enough and class is high enough, predictions would be above 1
#logistic regression solves the problem of 1+ and negative results

### How would we do this with Logistic Regression?

In [55]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train_imputed, y_train)
threshold = 0.5
(log_reg.predict_proba(X_test_imputed)[:,1] > threshold).astype(int)

C:\Users\lilyx\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,

In [56]:
manual_predictions = (log_reg.predict_proba(X_test_imputed)[:,1] > threshold).astype(int)
direct_predictions = log_reg.predict(X_test_imputed)
all(manual_predictions == direct_predictions)
#behind the scenes, you can set your own threshold, from discrete probabilities
# to actual predictions
# you can make tradeoffs

True

In [58]:
#Different metrics from classification vs regression
#Accuracy makes sense for classification
#R-squared makes sense for regression
score = log_reg.score(X_train_imputed,y_train)
print('Train Accuracy Score', score)

Train Accuracy Score 0.7048260381593715


In [59]:
y_pred = log_reg.predict(X_train_imputed)

In [60]:
len(y_pred)

891

In [61]:
len(y_train)

891

In [62]:
y_pred[:5]

array([0, 1, 0, 1, 0], dtype=int64)

In [64]:
y_train[:5].values

array([0, 1, 1, 1, 0], dtype=int64)

In [65]:
correct_predictions = 4
total_predictions = 5
accuracy = correct_predictions / total_predictions
print(accuracy)

0.8


In [66]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train[:5], y_pred[:5])

0.8

In [68]:
score = log_reg.score(X_test_imputed, y_test)#we don't have this information
print('Test Accuracy Score', score)#kaggle locked it away

NameError: name 'y_test' is not defined

In [69]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(log_reg, X_train_imputed, y_train, cv=10)
print('Cross-Validation Accuracy Scores', scores)#model accuracy is the range of these numbers, the sum of which is the mean

Cross-Validation Accuracy Scores [0.63333333 0.62222222 0.70786517 0.69662921 0.68539326 0.70786517
 0.73033708 0.75280899 0.71910112 0.71590909]


C:\Users\lilyx\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lilyx\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lilyx\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lilyx\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lilyx\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence t

In [70]:
scores = pd.Series(scores)
scores.min(), scores.mean(), scores.max()

(0.6222222222222222, 0.6971464646464647, 0.7528089887640449)

In [71]:
X_train_imputed.shape

(891, 3)

In [72]:
y_pred = log_reg.predict(X_train_imputed)

In [90]:
log_reg.coef_

array([[-0.83658924, -0.0315505 ,  0.00535274]])

In [ ]:
log_reg.intercept_

### How accurate is the Logistic Regression?

### What's the math for the Logistic Regression?

https://en.wikipedia.org/wiki/Logistic_function

https://en.wikipedia.org/wiki/Logistic_regression#Probability_of_passing_an_exam_versus_hours_of_study

In [73]:
log_reg.coef_

array([[-0.83658924, -0.0315505 ,  0.00535274]])

In [74]:
log_reg.intercept_

array([2.16897017])

In [75]:
def sigmoid(x):
    return 1 / (1 + np.e**(-x))
#The logistic sigmoids 'squishing' function,
#implemented to work with numpy arrays

In [76]:
np.dot(log_reg.coef_, test_case)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [78]:
test_case.T

array([[  1],
       [  5],
       [500]])

In [82]:
sigmoid(np.dot(log_reg.coef_, test_case.T) + log_reg.intercept_)
#dot product

array([[0.97918401]])

In [83]:
log_reg.predict_proba(test_case)

array([[0.02081599, 0.97918401]])

In [84]:
sigmoid(log_reg.coef_ @ test_case.T + log_reg.intercept_)

array([[0.97918401]])

## Feature Engineering

Get the [Category Encoder](http://contrib.scikit-learn.org/categorical-encoding/) library

If you're running on Google Colab:

```
!pip install category_encoders
```

If you're running locally with Anaconda:

```
!conda install -c conda-forge category_encoders
```

In [85]:
import seaborn as sns
sns_titanic = sns.load_dataset('titanic')


In [86]:
sns_titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [87]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [106]:
#how to engineer adult males that are alone
#where does sex = male
def make_features(X):
    X = X.copy()
    X['adult_male'] = (X['Sex'] == 'male') & (X['Age'] >= 16)
    X['alone'] = (X['SibSp'] == 0) & (X['Parch'] == 0)
    X['last_name'] = X['Name'].str.split(',').str[0]
    X['title'] = X['Name'].str.split(',').str[1].str.split('.').str[0]#feature extraction
    return X 
# train['adult_male'] = (train['Sex'] == 'male') & (train['Age'] >= 16)

In [107]:
train = make_features(train)
test = make_features(test)

In [108]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  adult_male  alone  \
0      0         A/5 21171   7.2500   NaN        S        True  False   
1      0          PC 17599  71.2833   C85        C       False  False   
2      0  STON/O2. 3101282   7.9250   NaN        S       False   True   
3      0            113803  53.1000  C123        S       False  False   
4      0            373450   8.0500   NaN        S        True   True   

   last_name  title  
0     Braund     Mr  
1    Cumings    Mrs  
2  Heikkinen   Miss  
3   Futrelle    Mrs  
4      Allen     Mr

In [109]:
 train['alone'].value_counts()

True     537
False    354
Name: alone, dtype: int64

In [110]:
train['adult_male'].value_counts()

False    478
True     413
Name: adult_male, dtype: int64

In [111]:
train['title'].value_counts()

 Mr              517
 Miss            182
 Mrs             125
 Master           40
 Dr                7
 Rev               6
 Major             2
 Col               2
 Mlle              2
 Lady              1
 Jonkheer          1
 the Countess      1
 Mme               1
 Sir               1
 Ms                1
 Capt              1
 Don               1
Name: title, dtype: int64

In [94]:
sns_titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [112]:
#it's best to do both tree ensemble and do feature engineering

In [ ]:
#categorical encoding means converting raw data into workable code like gender to 0 and 1

## Assignment: real-world classification

We're going to check out a larger dataset - the [FMA Free Music Archive data](https://github.com/mdeff/fma). It has a selection of CSVs with metadata and calculated audio features that you can load and try to use to classify genre of tracks. To get you started:

### Get and unzip the data

#### Google Colab

In [0]:
!wget https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
!unzip fma_metadata.zip

#### Windows
- Download the [zip file](https://os.unil.cloud.switch.ch/fma/fma_metadata.zip)
- You may need to use [7zip](https://www.7-zip.org/download.html) to unzip it


#### Mac
- Download the [zip file](https://os.unil.cloud.switch.ch/fma/fma_metadata.zip)
- You may need to use [p7zip](https://superuser.com/a/626731) to unzip it

### Look at first 3 lines of raw file

In [0]:
!head -n 3 fma_metadata/tracks.csv

### Read with pandas
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

In [119]:
df = pd.read_csv('tracks.csv', header=[0,1], index_col=0, infer_datetime_format = True)

### Fit Logistic Regression!

In [120]:
df.head()

album                                                     \
         comments         date_created        date_released engineer   
track_id                                                               
2               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
3               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
5               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
10              0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN   
20              0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN   

                                                                          \
         favorites id                                information listens   
track_id                                                                   
2                4  1                                    <p></p>    6073   
3                4  1                                    <p></p>    6073   
5                4  1                                    <p></p>    6073   
10               4  6                                        NaN   47632   
20               2  4  <p> "spiritual songs" from Nicky Cook</p>    2710   

                        ...       track                         \
         producer tags  ... information interest language_code   
track_id                ...                                      
2             NaN   []  ...         NaN     4656            en   
3             NaN   []  ...         NaN     1470            en   
5             NaN   []  ...         NaN     1933            en   
10            NaN   []  ...         NaN    54881            en   
20            NaN   []  ...         NaN      978            en   

                                                                              \
                                                    license listens lyricist   
track_id                                                                       
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN   
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN   
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN   
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN   
20        Attribution-NonCommercial-NoDerivatives (aka M...     361      NaN   

                                                 
         number publisher tags            title  
track_id                                         
2             3       NaN   []             Food  
3             4       NaN   []     Electric Ave  
5             6       NaN   []       This World  
10            1       NaN   []          Freeway  
20            3       NaN   []  Spiritual Level  

[5 rows x 52 columns]

In [124]:
dflist = df.columns.tolist()

In [132]:
dflist[::-1]

[('track', 'title'),
 ('track', 'tags'),
 ('track', 'publisher'),
 ('track', 'number'),
 ('track', 'lyricist'),
 ('track', 'listens'),
 ('track', 'license'),
 ('track', 'language_code'),
 ('track', 'interest'),
 ('track', 'information'),
 ('track', 'genres_all'),
 ('track', 'genres'),
 ('track', 'genre_top'),
 ('track', 'favorites'),
 ('track', 'duration'),
 ('track', 'date_recorded'),
 ('track', 'date_created'),
 ('track', 'composer'),
 ('track', 'comments'),
 ('track', 'bit_rate'),
 ('set', 'subset'),
 ('set', 'split'),
 ('artist', 'wikipedia_page'),
 ('artist', 'website'),
 ('artist', 'tags'),
 ('artist', 'related_projects'),
 ('artist', 'name'),
 ('artist', 'members'),
 ('artist', 'longitude'),
 ('artist', 'location'),
 ('artist', 'latitude'),
 ('artist', 'id'),
 ('artist', 'favorites'),
 ('artist', 'date_created'),
 ('artist', 'comments'),
 ('artist', 'bio'),
 ('artist', 'associated_labels'),
 ('artist', 'active_year_end'),
 ('artist', 'active_year_begin'),
 ('album', 'type'),
 ('

This dataset is bigger than many you've worked with so far, and while it should fit in Colab, it can take awhile to run. That's part of the challenge!

Your tasks:
- Clean up the variable names in the dataframe
- Use logistic regression to fit a model predicting (primary/top) genre
- Inspect, iterate, and improve your model
- Answer the following questions (written, ~paragraph each):
  - What are the best predictors of genre?
  - What information isn't very useful for predicting genre?
  - What surprised you the most about your results?

*Important caveats*:
- This is going to be difficult data to work with - don't let the perfect be the enemy of the good!
- Be creative in cleaning it up - if the best way you know how to do it is download it locally and edit as a spreadsheet, that's OK!
- If the data size becomes problematic, consider sampling/subsetting, or [downcasting numeric datatypes](https://www.dataquest.io/blog/pandas-big-data/).
- You do not need perfect or complete results - just something plausible that runs, and that supports the reasoning in your written answers

If you find that fitting a model to classify *all* genres isn't very good, it's totally OK to limit to the most frequent genres, or perhaps trying to combine or cluster genres as a preprocessing step. Even then, there will be limits to how good a model can be with just this metadata - if you really want to train an effective genre classifier, you'll have to involve the other data (see stretch goals).

This is real data - there is no "one correct answer", so you can take this in a variety of directions. Just make sure to support your findings, and feel free to share them as well! This is meant to be practice for dealing with other "messy" data, a common task in data science.

## Resources and stretch goals

- Check out the other .csv files from the FMA dataset, and see if you can join them or otherwise fit interesting models with them
- [Logistic regression from scratch in numpy](https://blog.goodaudience.com/logistic-regression-from-scratch-in-numpy-5841c09e425f) - if you want to dig in a bit more to both the code and math (also takes a gradient descent approach, introducing the logistic loss function)
- Create a visualization to show predictions of your model - ideally show a confidence interval based on error!
- Check out and compare classification models from scikit-learn, such as [SVM](https://scikit-learn.org/stable/modules/svm.html#classification), [decision trees](https://scikit-learn.org/stable/modules/tree.html#classification), and [naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html). The underlying math will vary significantly, but the API (how you write the code) and interpretation will actually be fairly similar.
- Sign up for [Kaggle](https://kaggle.com), and find a competition to try logistic regression with
- (Not logistic regression related) If you enjoyed the assignment, you may want to read up on [music informatics](https://en.wikipedia.org/wiki/Music_informatics), which is how those audio features were actually calculated. The FMA includes the actual raw audio, so (while this is more of a longterm project than a stretch goal, and won't fit in Colab) if you'd like you can check those out and see what sort of deeper analysis you can do.